name: Deploy Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd expense-manager-backend
        npm install
        
    - name: Run tests
      run: |
        cd expense-manager-backend
        npm test
        
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        cd expense-manager-backend
        npm run build
        # Add your deployment commands here
        # For example, if using a cloud provider:
        # - Configure your deployment platform
        # - Set up environment variables
        # - Deploy the application 